Refactor/exception handler) Exception Handler 구현
ToyVallet/swifty-backend pull request #43
Opened 2024-02-25 14:45 UTC by su-giana

# What is this PR for?
- Exception Handler 구현

# What has changed?
- Exception Handler 구현
- 사소한 버그 수정
- controller에 있었던 UUID 파싱 service layer로 옮김  (CustomerController)

# Anything to Contributors?
- ^^b

2024-02-25 15:25 UTC, threepebbles approved these changes, later dismissed
고생하셨습니다!

2024-02-25 15:25 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/exception/handler/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
이 부분은 ExceptionHandler 전체 경로가 들어갔네요!

2024-02-25 15:25 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/api/service/dto/Result.java
>  }
Result 클래스의 역할이 좀 더 커진 것 같은데요, 현재 코드에서는 클래스 이름을 StatusCode로 바꾸고 아예 status code 용도로 사용하는건 어떨까요?

2024-02-25 15:25 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/core/common/redis/entity/RefreshTokenCache.java
>      public RefreshTokenCache(UUID customerId, String refreshToken) {
Auth 클래스는 Mysql 에서 사용되는 Entity, RefreshTokenCache 클래스는 redis에서 사용되는 용도의 클래스로 일부러 구분지어놓은 것입니다!
`@Table`, `@Column`, `@Id`과 같은 annotation들은 Mysql에서 동작될 것이 예상되는 annotation들이라 혼용하는 것보다는 나눠놓는게 좋을 것 같아요~

2024-02-25 15:25 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/api/service/CustomerApiService.java
> +    ResponseResult<?> customerWithdrawal(String customerUuid);
나머지 `customerId`도 `customerUuid`로 변경해서 일관된 네이밍 사용하면 좋을 것 같아요~

2024-02-26 09:21 UTC, su-giana commented on src/main/java/com/swifty/bank/server/api/service/dto/Result.java
>  }
저는 비즈니스 용으로 하는게 나은 듯해요! 보통의 status 코드는 거의다 bad request이고 다른 것들은 자체 로직이나 -> 성공 등
exception 들에서 -> 401 등에서 잡을 수 있기 때문에 statusCode로 바꾸면 저는 중복되는 느낌을 받았습니다~

2024-02-26 09:22 UTC, su-giana commented on src/main/java/com/swifty/bank/server/exception/handler/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
오엠지 수정하겠습니다

2024-02-26 10:33 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/api/service/dto/Result.java
>  }
비즈니스용으로 사용하는데 200, 400은 왜 넣으신건가요? code 인스턴스의 의미가 없어보이는데요

2024-02-26 10:46 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/api/service/dto/Result.java
>  }
추가하신 controller 코드에서 이미 Result.FAIL이면 bad request, SUCCESS면 ok로 코드가 되어있는데 code 인스턴스가 의미가 있을까요?

2024-02-26 10:47 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/api/service/dto/Result.java
>  }
2xx, 4xx을 세분화해서 Result 클래스에 추가하면 어떨까요?
그러면 controller에서도 Result.code를 통해 status code를 구분해서 보낼 수 있어서 의미가 있어질 것 같습니다

2024-02-26 11:15 UTC, threepebbles requested changes
고생하셨습니다. 코멘트 확인 부탁드립니다

2024-02-26 11:15 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/core/common/redis/service/impl/RefreshTokenRefreshTokenRedisServiceImpl.java
> +public class RefreshTokenRefreshTokenRedisServiceImpl implements RefreshTokenRedisService {
여기 클래스 네이밍도 마찬가지입니다.

2024-02-26 11:15 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/core/common/redis/service/impl/OtpRefreshTokenRedisServiceImpl.java
> +public class OtpRefreshTokenRedisServiceImpl implements OtpRefreshTokenRedisService {
OtpRedisServcie는 refresh token이랑 아무 관련없는데 클래스명이 왜 이렇게 된 걸까요!
아마 클래스 이름 바꾸실 때 refactor기능을 안 쓰시고 파일 전체에서 replace 기능 쓰셔서 잘못 바뀐 것 같습니다
수정부탁드립니다.

2024-02-26 11:15 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/core/common/authentication/RefreshTokenDb.java
> +public class RefreshTokenDb extends BaseEntity {
흠 RefreshTokenDb하니까 뭔가 진짜 DB를 의미하는 것 같네요
그냥 RefreshToken은 어떨까요

2024-02-26 11:15 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/api/service/impl/CustomerApiServiceImpl.java
>      private final BCryptPasswordEncoder encoder;
`BCryptPasswordEncoder`를 이용한 비밀번호 해싱 좋아보입니다 👍

2024-02-26 11:15 UTC, threepebbles commented on src/main/java/com/swifty/bank/server/core/common/redis/entity/RefreshTokenCache.java
> +public class RefreshTokenCache extends BaseEntity {
`RefreshTokenCache`는 Mysql 엔티티로 쓰일 클래스가 아니라 BaseEntity를 상속 받으면 안됩니다!

2024-02-27 04:06 UTC, threepebbles approved these changes

2024-02-27 04:13 UTC, threepebbles commented
LGTM 😊 고생하셨습니다
comment가 반영된 부분은 comment 별로 `resolve conversation` 눌러서 완료됐음을 표시해주시면 감사하겠습니다

2024-02-27 04:24 UTC, merged